Repository de6-pipeguys/olvy-crawling, pull requests merged in 2025-07, with the labels that each got.

#5 [docs/github-setup] ruff.toml 파일 내 내용 추가 (exclude, indent-width, Formatter configuration)
  .github/ruff.toml
Labels: documentation

#6 docs: modify auto-correct code blocks within a ruff-guide
  docs/ruff-guide.md
Labels: documentation

#11 chore: add to .gitignore
  .gitignore
Labels: documentation, good first issue

#9 Feature/crawl skincare
  Dockerfile
  crawlers/skincare/crawl_brand_skincare.py
  crawlers/skincare/crawl_rank_skincare.py
  requirements.txt
Labels: enhancement, good first issue
